apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-bot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-bot
  template:
    metadata:
      labels:
        app: chat-bot
    spec:
      containers:
        - name: chat-bot-container
          image: chat-bot:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
